# Generated by Django 4.2.4 on 2023-11-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_car_owner_alter_registration_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main_app.owner'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
        ),
    ]
