# Generated by Django 4.2.4 on 2023-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_lecturerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.lecturer'),
        ),
    ]
