# Generated by Django 4.2.4 on 2023-10-24 13:43

from django.db import migrations


def add_brand(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brand_model = apps.get_model('main_app', 'UniqueBrand')

    unique_shoe_brands = shoe.objects.all().values_list('brand', flat=True).distinct()

    for brand in unique_shoe_brands:
        unique_brand_model.objects.create(brand_name=brand)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrand'),
    ]

    operations = [
        migrations.RunPython(add_brand)
    ]
