# Generated by Django 4.2.4 on 2023-10-25 16:43

from django.db import migrations


def set_price(apps, schema_editor):
    smg_model = apps.get_model('main_app', 'Smartphone')

    all_smgs = smg_model.objects.all()

    for smg in all_smgs:
        smg.price = len(smg.brand) * 120
        smg.save()


def set_category(apps, schema_editor):
    smg_model = apps.get_model('main_app', 'Smartphone')

    al_smgs = smg_model.objects.all()

    for smg in al_smgs:
        if smg.price >= 750:
            smg.category = 'Expensive'
        else:
            smg.category = 'Cheap'
        smg.save()


def set_price_and_category_unified(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_migration(apps, schema_editor):
    smg_model = apps.get_model('main_app', 'Smartphone')

    all_smgs = smg_model.objects.all()

    for smg in all_smgs:
        smg.price = 1
        smg.category = 'no category'
        smg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category_unified, reverse_migration)
    ]
