# Generated by Django 4.2.4 on 2023-10-25 17:14

from django.db import migrations
import datetime


def set_delivery_or_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'P':
            order.delivery = order.order_date + datetime.timedelta(days=3)
            order.save()
        elif order.status == 'C':
            order.warranty = '24 months'
            order.save()
        else:
            order.delete()


def reverse_migration(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'P':
            order.delivery = None
        elif order.status == 'C':
            order.warranty = 'no warranty'
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_or_warranty, reverse_migration)
    ]
