# Generated by Django 4.2.4 on 2023-11-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mage',
            old_name='spell_book',
            new_name='spellbook_type',
        ),
    ]
