# Generated by Django 4.2.4 on 2023-11-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_spell_book_mage_spellbook_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viperassassin',
            old_name='venomous_strike_mastery',
            new_name='venomous_strikes_mastery',
        ),
    ]
